// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/suggestions/CardHoverOverlay.tsx": () => import("../components/mockups/suggestions/CardHoverOverlay.tsx"),
  "./components/mockups/suggestions/GenreFilter.tsx": () => import("../components/mockups/suggestions/GenreFilter.tsx"),
  "./components/mockups/suggestions/HeroBackdrop.tsx": () => import("../components/mockups/suggestions/HeroBackdrop.tsx"),
  "./components/mockups/suggestions/SearchAutocomplete.tsx": () => import("../components/mockups/suggestions/SearchAutocomplete.tsx"),
  "./components/mockups/suggestions/SynopsisCleanup.tsx": () => import("../components/mockups/suggestions/SynopsisCleanup.tsx"),
  "./components/mockups/suggestions/UpcomingPage.tsx": () => import("../components/mockups/suggestions/UpcomingPage.tsx")
};
